export const ErrorCodes = {
  // Common
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  FORBIDDEN: "FORBIDDEN",

  // Auth
  PASSWORDS_DO_NOT_MATCH: "PASSWORDS_DO_NOT_MATCH",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE",
  PHONE_NUMBER_ALREADY_IN_USE: "PHONE_NUMBER_ALREADY_IN_USE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  // Booking
  INVALID_RIDE_ID: "INVALID_RIDE_ID",
  RIDE_NOT_FOUND: "RIDE_NOT_FOUND",
  RIDE_NOT_AVAILABLE: "RIDE_NOT_AVAILABLE",
  DRIVER_CANNOT_BOOK_OWN_RIDE: "DRIVER_CANNOT_BOOK_OWN_RIDE",
  USER_ALREADY_IN_RIDE: "USER_ALREADY_IN_RIDE",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  UNAUTHORIZED_ACCEPT_BOOKING: "UNAUTHORIZED_ACCEPT_BOOKING",
  BOOKING_NOT_PENDING_ACCEPT: "BOOKING_NOT_PENDING_ACCEPT",
  RIDE_FOR_BOOKING_NOT_FOUND: "RIDE_FOR_BOOKING_NOT_FOUND",
  RIDE_NOT_BOOKABLE: "RIDE_NOT_BOOKABLE",
  UNAUTHORIZED_DECLINE_BOOKING: "UNAUTHORIZED_DECLINE_BOOKING",
  BOOKING_NOT_PENDING_DECLINE: "BOOKING_NOT_PENDING_DECLINE",
  UNAUTHORIZED_VIEW_BOOKINGS: "UNAUTHORIZED_VIEW_BOOKINGS",
  UNAUTHORIZED_CANCEL_BOOKING: "UNAUTHORIZED_CANCEL_BOOKING",
  BOOKING_CANNOT_CANCEL: "BOOKING_CANNOT_CANCEL",

  // Ride
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INCOMPLETE_PROFILE: "INCOMPLETE_PROFILE",
  RIDE_ALREADY_CANCELLED: "RIDE_ALREADY_CANCELLED",
  CANNOT_CANCEL_COMPLETED_RIDE: "CANNOT_CANCEL_COMPLETED_RIDE",
  UNAUTHORIZED_DELETE_RIDE: "UNAUTHORIZED_DELETE_RIDE",
  UNAUTHORIZED_UPDATE_RIDE: "UNAUTHORIZED_UPDATE_RIDE",
  CANNOT_EDIT_COMPLETED_RIDE: "CANNOT_EDIT_COMPLETED_RIDE",
  CANNOT_EDIT_CANCELLED_RIDE: "CANNOT_EDIT_CANCELLED_RIDE",
  DEPARTURE_TIME_MUST_BE_FUTURE: "DEPARTURE_TIME_MUST_BE_FUTURE",
  CANNOT_REDUCE_SEATS: "CANNOT_REDUCE_SEATS",

  // User
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  UNAUTHORIZED_VIEW_PROFILE: "UNAUTHORIZED_VIEW_PROFILE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
